# Generated by Django 5.2.17 on 2026-09-25 10:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('COUNSELLOR', 'Counsellor')], db_index=True, default='COUNSELLOR', max_length=20)),
                ('title', models.CharField(default='Officer', help_text='Display title, e.g., Sr. Officer, Officer, Preferred, Junior', max_length=100)),
                ('avatar', models.URLField(blank=True, help_text='Profile photo or studio headshot URL', max_length=500, null=True)),
                ('specialization', models.CharField(blank=True, help_text='Program domain specialization (e.g. BCA & Tech Specialist)', max_length=255, null=True)),
                ('max_capacity', models.PositiveIntegerField(default=40, help_text='Maximum active lead handling limit for round-robin allocation')),
                ('is_paused', models.BooleanField(default=False, help_text='When true, counsellor is paused from receiving automated round-robin lead allocation')),
                ('today_target', models.PositiveIntegerField(default=8, help_text='Daily admissions confirmation target')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['name'],
            },
        ),
    ]
